title: Tự động hóa
description: Trang web để chia sẻ về tự động hóa công nghiệp
baseurl: "" # the subpath of your site, e.g. /blog
url: davisnguyen111195.github.com/tudonghoa # the base hostname & protocol for your site, e.g. http://example.com

title-separator: "-"

author:
  name: davidnguyen
  github: davidnguyen
  facebook: phi.mai.129
  email: nguyendat111195@gmail.com


# Build settings
timezone: "Europe/Paris"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: /:categories/:title
# paginate: 24
# paginate_path: "/thought/page-:num"

# Facebook App ID
# fb_app_id: ""

sass:
  style: compact

exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME

plugins:
  - jekyll-feed
